# Generated by Django 6.1.1 on 2026-09-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('level', models.CharField(blank=True, choices=[('bachelors degree', "Bachelor's Degree"), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('secondary', 'Secondary Education')], max_length=20)),
                ('start_date', models.DateField()),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, to='projects.skill')),
                ('technologies', models.ManyToManyField(blank=True, to='projects.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, to='projects.skill')),
                ('technologies', models.ManyToManyField(blank=True, to='projects.technology')),
            ],
        ),
    ]
